stages:
  - build

variables:
  IMAGE_NAME: "jonashonecker/feedpaper"
  IMAGE_TAG: "latest"

build_image:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  script:
    - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker build -t "$IMAGE_NAME:$CI_COMMIT_SHA" .
    - docker tag "$IMAGE_NAME:$CI_COMMIT_SHA" "$IMAGE_NAME:$IMAGE_TAG"
    - docker push "$IMAGE_NAME:$IMAGE_TAG"
  only:
    - main
    - tags
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
