helmDefaults:
  createNamespace: true

releases:
  - name: feedpaper
    namespace: feedpaper
    chart: oci://ghcr.io/rarosalion/charts/feedpaper
    version: "0.2.0"
    values:
      - ./helm/feedpaper/values.yaml
