{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "feedpaper.fullname" . }}-output
  labels:
    app.kubernetes.io/name: {{ include "feedpaper.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if eq .Values.persistence.type "s3" }}
  storageClassName: ""
  volumeName: {{ include "feedpaper.fullname" . }}-output-pv
  {{- else if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
{{- end }}
