{{- if or .Values.mail.smtpUsername .Values.mail.smtpPassword .Values.mail.to .Values.mail.from -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "feedpaper.fullname" . }}-mail
type: Opaque
stringData:
  smtp-username: {{ .Values.mail.smtpUsername | quote }}
  smtp-password: {{ .Values.mail.smtpPassword | quote }}
{{- end }}
