image:
  repository: rarosalion/feedpaper-docker
  tag: "v0.2.0"
  pullPolicy: IfNotPresent

feedpaper:
  schedule: "0 6 * * *"
  timezone: UTC
  outputDir: /output
  keepUnread: false
  extraArgs: []
  config:
    email: ""
    password: ""
    excludes: []

mail:
  enabled: false
  to: ""
  from: ""
  subject: "feedpaper newspaper"
  smtpHost: ""
  smtpPort: 587
  smtpStartTls: true
  smtpUsername: ""
  smtpPassword: ""

cronjob:
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  suspend: false
  pod:
    annotations: {}
    labels: {}
    resources: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}
    securityContext: {}

persistence:
  enabled: true
  type: pvc # pvc | s3
  size: 1Gi
  accessMode: ReadWriteOnce
  storageClass: ""
  s3:
    bucketName: ""
    endpointUrl: ""
    region: default
    fileMode: "666"
    dirMode: "777"
    extraMountOptions: []

nameOverride: ""
fullnameOverride: ""
